sudo: false
language: python
env:
  matrix:
  - TESTENV=py26
  - TESTENV=py27
  - TESTENV=py34
  - TESTENV=coveralls
install:
- pip install tox
script: tox -e $TESTENV
notifications:
    email:
        - bubenkoff@gmail.com
        - oleg.pidsadnyi@gmail.com
